# Generated by Django 5.2.1 on 2025-05-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('agno2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('invoice_id', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('paid', 'Paid'),
                            ('overdue', 'Overdue'),
                            ('cancelled', 'Cancelled'),
                        ],
                        max_length=20,
                    ),
                ),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invoices',
                        to='agno2.user',
                    ),
                ),
            ],
            options={
                'db_table': 'invoices',
                'indexes': [
                    models.Index(fields=['invoice_id'], name='invoices_invoice_56eb80_idx'),
                    models.Index(fields=['user', 'status'], name='invoices_user_id_9940be_idx'),
                    models.Index(fields=['due_date'], name='invoices_due_dat_039a25_idx'),
                ],
            },
        ),
    ]
