# Generated by Django 5.1.7 on 2025-05-10 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('account_status', models.CharField(max_length=50)),
                ('registration_date', models.DateTimeField()),
                ('plan_name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(max_length=50)),
                ('subscription_start_date', models.DateTimeField()),
                ('subscription_renewal_date', models.DateTimeField()),
                ('auto_renewal', models.BooleanField(default=True)),
                ('voice_enabled', models.BooleanField(default=True)),
                ('data_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('roaming_enabled', models.BooleanField(default=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('billing_cycle', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'billing_address',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='api.billingaddress',
                    ),
                ),
            ],
            options={
                'db_table': 'users',
                'indexes': [
                    models.Index(fields=['email'], name='users_email_4b85f2_idx'),
                    models.Index(fields=['customer_id'], name='users_custome_e6ad80_idx'),
                ],
            },
        ),
    ]
